# Generated by Django 3.2 on 2021-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
